---
- name: Install java17
  ansible.builtin.apt:
    name: default-jre
    state: present
    update_cache: yes

- name: Ensure group "kafka" exists
  ansible.builtin.group:
    name: "{{ kafka_group }}"
    state: present

- name: Create kafka user
  ansible.builtin.user:
    name: "{{ kafka_user }}"
    group: "{{ kafka_group }}"
    shell: /usr/sbin/nologin
    system: yes
    state: present

- name: Create a kafka_home_dir
  ansible.builtin.file:
    path: "{{ kafka_home_dir }}"
    state: directory
    mode: '0750'
    owner: "{{ kafka_user }}"
    group: "{{ kafka_group }}"

- name: Create a directory kafka_config_dir
  ansible.builtin.file:
    path: "{{ kafka_config_dir }}"
    state: directory

- name: Download kafka tgz
  get_url:
    url: "https://dlcdn.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz"
    dest: "/tmp/kafka_2.13-3.9.0.tgz"

- name: Extract Kafka tarball with strip-components
  unarchive:
    src: /tmp/kafka_2.13-3.9.0.tgz
    dest: "{{ kafka_home_dir }}"
    remote_src: yes
    extra_opts: 
      - --strip-components=1
  become: yes