---
- name: Install java and download kafka
  import_tasks: install.yml

- name: Install and start kafka broker
  import_tasks: broker.yml

- name: Install and start kafka controller
  import_tasks: controller.yml
