---
- name: Создать директорию /usr/share/man/man1 (если отсутствует)
  file:
    path: /usr/share/man/man1
    state: directory
    mode: '0755'
  become: yes

- name: Install java17
  ansible.builtin.apt:
    name: default-jre
    state: present
    update_cache: yes

- name: Ensure group "kafka" exists
  ansible.builtin.group:
    name: kafka
    state: present

- name: Create kafka user
  ansible.builtin.user:
    name: kafka
    group: kafka
    shell: /usr/sbin/nologin
    system: yes
    state: present

- name: Create a directory /usr/local/share/kafka
  ansible.builtin.file:
    path: /usr/local/share/kafka
    state: directory
    mode: '0750'
    owner: kafka
    group: kafka

- name: Download kafka tgz
  get_url:
    url: "https://dlcdn.apache.org/kafka/3.9.0/kafka_2.13-3.9.0.tgz"
    dest: "/tmp/kafka_2.13-3.9.0.tgz"

- name: Extract Kafka tarball with strip-components
  unarchive:
    src: /tmp/kafka_2.13-3.9.0.tgz
    dest: /usr/local/share/kafka
    remote_src: yes
    extra_opts: 
      - --strip-components=1
  become: yes

- name: Create a directory /etc/kafka
  ansible.builtin.file:
    path: /etc/kafka
    state: directory

- name: Create a directory /tmp/kraft-combined-logs
  ansible.builtin.file:
    path: /tmp/kraft-combined-logs
    state: directory
    mode: '0750'
    owner: kafka
    group: kafka

- name: Deploy Kafka configuration file
  template:
    src: server.properties.j2
    dest: /etc/kafka/server.properties
    owner: root
    group: kafka
    mode: '0640'

- name: Deploy systemd unit file
  template:
    src: kafka.service.j2
    dest: /etc/systemd/system/kafka.service
    
- name: Format Kafka storage with generated cluster ID
  command: /usr/local/share/kafka/bin/kafka-storage.sh format --ignore-formatted --standalone -t {{ kafka_uuid }} -c /etc/kafka/server.properties

- name: Ensure /tmp/kraft-combined-logs and its contents have correct permissions
  ansible.builtin.file:
    path: /tmp/kraft-combined-logs
    state: directory
    mode: '0750'
    owner: kafka
    group: kafka
    recurse: yes

- name: Just force systemd to reread configs
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: start kafka
  ansible.builtin.systemd_service:
    name: kafka.service
    state: started
    enabled: true