#SPDX-License-Identifier: MIT-0
---
- name: restart kafka broker
  ansible.builtin.systemd_service:
    name: kafka-broker.service
    state: restarted

- name: restart kafka controller
  ansible.builtin.systemd_service:
    name: kafka-controller.service
    state: restarted
